# Generated by Django 4.2.1 on 2023-05-13 16:14

from django.db import migrations


def populate_role(apps ,schemaeditor):
    entries = {
        "Feeder": "Feed the animals",
        "Cleaner":"Cleans animals",
        "Trainer":"Train the animals"
    }
    Roles = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role = Roles(naem=key, description=value)
        role.save()

def populate_dept(apps ,schemaeditor):
    entries = {
        "Food":"Take care of animal dietery requirements",
        "Health":"Handle health and care of animal well being",
        "Maintenence":"handle and maintain equipment and custodial duties"
    }
    Dept = apps.get_model("accounts", "Department")
    for key, value in entries.items():
        dept = Dept(name=key, description=value)
        dept.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_role),
        migrations.RunPython(populate_dept),
    ]
