# Generated by Django 4.2.1 on 2023-05-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230513_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='naem',
            new_name='name',
        ),
    ]
